# Serving
# detach:  false
port:    8888
host:    0.0.0.0
# baseurl: "/JavenBlog" # does not include hostname

#
title:            Javen Blog
description:      Just To Share
# safe:             false
# auto:             false
# jekyll serve:     false
# port:             4000
# baseurl:          /JavenBlog
# url:              http://jingelzfqq.github.io
# signoff:          Javen# Your name.
# disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
# facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
# google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.


links:
  - name:         About
    url:          /about
  # - name:         Blog
  #   url:          http://muan.co
  #   external:     true
  - name:         Email
    url:          mailto:412775083@qq.com
    external:     true
  - name:         GitHub
    url:          http://github.com/jingelzfqq
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
