highlighter: pygments

# 作者信息
author:
  name: Javen Liu
  email: 412775083@qq.com
  # link: http://zhenchen.me
  # weibo: http://weibo.com/markchentl
  github: http://github.com/jingelzfqq

# 站点信息
title: Javen Blog
description: Javen的博客
# url: http://zhenchen.me
language: 中文

exclude: ['vendor', 'README.md', 'Gemfile', 'Gemfile.lock', 'config.ru', 'unicorn.rb', 'Procfile']
